export const SIGNUP_IN_PROGRESS = 'SIGNUP_IN_PROGRESS';
export const SIGNUP_SUCCESSFULLY = 'SIGNUP_SUCCESSFULLY';
export const SIGNUP_WITH_ERRORS = 'SIGNUP_WITH_ERRORS';

export const LOGIN_IN_PROGRESS = 'LOGIN_IN_PROGRESS';
export const LOGIN_SUCCESSFULLY = 'LOGIN_SUCCESSFULLY';
export const LOGIN_WITH_ERRORS = 'LOGIN_WITH_ERRORS';

export const LOGIN_CALLBACK_IN_PROGRESS = 'LOGIN_CALLBACK_IN_PROGRESS';
export const LOGIN_CALLBACK_SUCCESSFULLY = 'LOGIN_CALLBACK_SUCCESSFULLY';
export const LOGIN_CALLBACK_WITH_ERRORS = 'LOGIN_CALLBACK_WITH_ERRORS';

export const LOGOUT_IN_PROGRESS = 'LOGOUT_IN_PROGRESS';
export const LOGOUT_SUCCESSFULLY = 'LOGOUT_SUCCESSFULLY';
export const LOGOUT_WITH_ERRORS = 'LOGOUT_WITH_ERRORS';

export const PROFILE_IN_PROGRESS = 'PROFILE_IN_PROGRESS';
export const PROFILE_SUCCESSFULLY = 'PROFILE_SUCCESSFULLY';
export const PROFILE_WITH_ERRORS = 'PROFILE_WITH_ERRORS';
