export const PROFILE_IN_PROGRESS = 'PROFILE_IN_PROGRESS';
export const PROFILE_SUCCESSFULLY = 'PROFILE_SUCCESSFULLY';
export const PROFILE_WITH_ERRORS = 'PROFILE_WITH_ERRORS';

export const ADD_ANIME_TO_LIST_IN_PROGRESS = 'ADD_ANIME_TO_LIST_IN_PROGRESS';
export const ADD_ANIME_TO_LIST_SUCCESSFULLY = 'ADD_ANIME_TO_LIST_SUCCESSFULLY';
export const ADD_ANIME_TO_LIST_WITH_ERRORS = 'ADD_ANIME_TO_LIST_WITH_ERRORS';

export const FECTH_ANIME_INFO_IN_PROGRESS = 'FECTH_ANIME_INFO_IN_PROGRESS';
export const FECTH_ANIME_INFO_SUCCESSFULLY = 'FECTH_ANIME_INFO_SUCCESSFULLY';
export const FECTH_ANIME_INFO_WITH_ERRORS = 'FECTH_ANIME_INFO_WITH_ERRORS';
