export const PROFILE_IN_PROGRESS = 'PROFILE_IN_PROGRESS';
export const PROFILE_SUCCESSFULLY = 'PROFILE_SUCCESSFULLY';
export const PROFILE_WITH_ERRORS = 'PROFILE_WITH_ERRORS';

export const USER_ANIME_LISTS_IN_PROGRESS = 'USER_ANIME_LISTS_IN_PROGRESS';
export const USER_ANIME_LISTS_SUCCESSFULLY = 'USER_ANIME_LISTS_SUCCESSFULLY';
export const USER_ANIME_LISTS_WITH_ERRORS = 'USER_ANIME_LISTS_WITH_ERRORS';

export const ADD_ANIME_TO_LIST_IN_PROGRESS = 'ADD_ANIME_TO_LIST_IN_PROGRESS';
export const ADD_ANIME_TO_LIST_SUCCESSFULLY = 'ADD_ANIME_TO_LIST_SUCCESSFULLY';
export const ADD_ANIME_TO_LIST_WITH_ERRORS = 'ADD_ANIME_TO_LIST_WITH_ERRORS';

export const DELETE_ANIME_FROM_LISTS_IN_PROGRESS =
    'DELETE_ANIME_FROM_LISTS_IN_PROGRESS';
export const DELETE_ANIME_FROM_LISTS_SUCCESSFULLY =
    'DELETE_ANIME_FROM_LISTS_SUCCESSFULLY';
export const DELETE_ANIME_FROM_LISTS_WITH_ERRORS =
    'DELETE_ANIME_FROM_LISTS_WITH_ERRORS';

export const FETCH_ANIME_INFO_IN_PROGRESS = 'FETCH_ANIME_INFO_IN_PROGRESS';
export const FETCH_ANIME_INFO_SUCCESSFULLY = 'FETCH_ANIME_INFO_SUCCESSFULLY';
export const FETCH_ANIME_INFO_WITH_ERRORS = 'FETCH_ANIME_INFO_WITH_ERRORS';

export const CHANGE_ANIME_STATUS_IN_PROGRESS =
    'CHANGE_ANIME_STATUS_IN_PROGRESS';
export const CHANGE_ANIME_STATUS_SUCCESSFULLY =
    'CHANGE_ANIME_STATUS_SUCCESSFULLY';
export const CHANGE_ANIME_STATUS_WITH_ERRORS =
    'CHANGE_ANIME_STATUS_WITH_ERRORS';
