export const FETCH_FULL_ANIME_INFO_IN_PROGRESS =
    'FETCH_FULL_ANIME_INFO_IN_PROGRESS';
export const FETCH_FULL_ANIME_INFO_SUCCESSFULLY =
    'FETCH_FULL_ANIME_INFO_SUCCESSFULLY';
export const FETCH_FULL_ANIME_INFO_WITH_ERRORS =
    'FETCH_FULL_ANIME_INFO_WITH_ERRORS';
