export const FETCH_TRENDING_IN_PROGRESS = 'FETCH_TRENDING_IN_PROGRESS';
export const FETCH_TRENDING_SUCCESSFULLY = 'FETCH_TRENDING_SUCCESSFULLY';
export const FETCH_TRENDING_WITH_ERRORS = 'FETCH_TRENDING_WITH_ERRORS';

export const SEARCH_INIT = 'SEARCH_INIT';
export const SEARCH_IN_PROGRESS = 'SEARCH_IN_PROGRESS';
export const SEARCH_SUCCESSFULLY = 'SEARCH_SUCCESSFULLY';
export const SEARCH_WITH_ERRORS = 'SEARCH_WITH_ERRORS';
