export const FETCH_POPULAR_IN_PROGRESS = 'FETCH_POPULAR_IN_PROGRESS';
export const FETCH_POPULAR_SUCCESSFULLY = 'FETCH_POPULAR_SUCCESSFULLY';
export const FETCH_POPULAR_WITH_ERRORS = 'FETCH_POPULAR_WITH_ERRORS';

export const SEARCH_INIT = 'SEARCH_INIT';
export const SEARCH_IN_PROGRESS = 'SEARCH_IN_PROGRESS';
export const SEARCH_SUCCESSFULLY = 'SEARCH_SUCCESSFULLY';
export const SEARCH_WITH_ERRORS = 'SEARCH_WITH_ERRORS';
