export const FETCH_POPULAR_IN_PROGRESS = 'FETCH_POPULAR_IN_PROGRESS';
export const FETCH_POPULAR_SUCCESSFULLY = 'FETCH_POPULAR_SUCCESSFULLY';
export const FETCH_POPULAR_WITH_ERRORS = 'FETCH_POPULAR_WITH_ERRORS';
