export const FETCH_HOME_IN_PROGRESS = 'FETCH_HOME_IN_PROGRESS';
export const FETCH_HOME_SUCCESSFULLY = 'FETCH_HOME_SUCCESSFULLY';
export const FETCH_HOME_WITH_ERRORS = 'FETCH_HOME_WITH_ERRORS';

export const SEARCH_INIT = 'SEARCH_INIT';
export const SEARCH_IN_PROGRESS = 'SEARCH_IN_PROGRESS';
export const SEARCH_SUCCESSFULLY = 'SEARCH_SUCCESSFULLY';
export const SEARCH_WITH_ERRORS = 'SEARCH_WITH_ERRORS';

export const FETCH_ANIME_LIST_IN_PROGRESS = 'FETCH_ANIME_LIST_IN_PROGRESS';
export const FETCH_ANIME_LIST_SUCCESSFULLY = 'FETCH_ANIME_LIST_SUCCESSFULLY';
export const FETCH_ANIME_LIST_WITH_ERRORS = 'FETCH_ANIME_LIST_WITH_ERRORS';
